### ISSUE TITLE
POIs outside D4

### ISSUE THREAD

**Issue by doorleyr** [CityScope/CSL_HCMC#10]
The POI data provided only cover District 4. However, some POIs outside of D4 will still be accessible from D4. Therefore, if we want to model, for example, 15 minute walking accessibility in D4, we need to also have information about POIs in the districts immediately surrounding D4.

**Comment by doorleyr** [comment]
@nqlong-vlab do you have any updates on this?

**Comment by nqlong-vlab** [comment]
@doorleyr : POI have updated ousite D4  in #14 , you can pull the new and review it. 
<img width="853" alt="Screen Shot 2021-06-14 at 01 15 50" src="https://user-images.githubusercontent.com/74805596/121817879-42154c80-ccae-11eb-8841-4396223eebac.png">
