### ISSUE TITLE
Building layer consistency

### ISSUE THREAD

**Issue by agrignard** [CityScope/CSL_HCMC#19]
In order to complete issue #1 there is still some atomic change that needs to be done concerning the building

Can you please change the file so we have the same consistency for each scenario as you can see here scenario 0 and 1 are covering district 4 + Surrounding but Scenario 2 and 3 are only providing the port area
Scenario 0
<img width="1237" alt="Screenshot 2021-06-15 at 11 17 57" src="https://user-images.githubusercontent.com/3928502/122027448-6a469d80-cdcb-11eb-958f-bd8760e27e84.png">
Scenario 1
<img width="1241" alt="Screenshot 2021-06-15 at 11 18 06" src="https://user-images.githubusercontent.com/3928502/122027476-6fa3e800-cdcb-11eb-86b6-075bc173153a.png">
Scenario 2
<img width="1238" alt="Screenshot 2021-06-15 at 11 18 12" src="https://user-images.githubusercontent.com/3928502/122027486-70d51500-cdcb-11eb-903d-27ecedac65d9.png">
Scenario 3
<img width="1239" alt="Screenshot 2021-06-15 at 11 18 19" src="https://user-images.githubusercontent.com/3928502/122027489-70d51500-cdcb-11eb-88d5-6819152ef492.png">

**Comment by nqlong-vlab** [comment]
Hi @agrignard , you should pull the latest commit in github. I have reviewed once again. Building data are full in 4 scenarios.
Scenario 0:
<img width="1012" alt="Screen Shot 2021-06-15 at 16 39 27" src="https://user-images.githubusercontent.com/74805596/122031093-8f053a00-cdf8-11eb-838e-ac24aef4cad5.png">
Scenario 1:
<img width="1012" alt="Screen Shot 2021-06-15 at 16 39 51" src="https://user-images.githubusercontent.com/74805596/122031127-9cbabf80-cdf8-11eb-99a5-f752ba5232f6.png">
Scenario 2:
<img width="1012" alt="Screen Shot 2021-06-15 at 16 39 56" src="https://user-images.githubusercontent.com/74805596/122031209-b22fe980-cdf8-11eb-90c0-58437dafdb06.png">
Scenario 3:
<img width="1012" alt="Screen Shot 2021-06-15 at 16 40 06" src="https://user-images.githubusercontent.com/74805596/122031243-b9ef8e00-cdf8-11eb-9830-597cdd6bb20a.png">

**Comment by agrignard** [comment]
Ok this is great indeed it's ok in the last commit
