### ISSUE TITLE
LandUse consistency 

### ISSUE THREAD

**Issue by agrignard** [CityScope/CSL_HCMC#21]
In order to complete issue #1 there is still some atomic change that needs to be done concerning the Landuse

Can you please change the file so we have the same consistency for each scenario as you can see here scenario 0 and 1 are covering district 4 + Surrounding but Scenario 2 and 3 are only providing the port area
Scenario 0
<img width="1223" alt="Screenshot 2021-06-15 at 11 25 35" src="https://user-images.githubusercontent.com/3928502/122028644-85fe7380-cdcc-11eb-9c6b-226143ebe6c2.png">
Scenario 1
<img width="1210" alt="Screenshot 2021-06-15 at 11 25 41" src="https://user-images.githubusercontent.com/3928502/122028671-8a2a9100-cdcc-11eb-96bf-4b978ae2f58e.png">
Scenario 2
<img width="1197" alt="Screenshot 2021-06-15 at 11 25 47" src="https://user-images.githubusercontent.com/3928502/122028677-8ac32780-cdcc-11eb-8b24-fc4cc6fa4963.png">
Scenario 3
<img width="1202" alt="Screenshot 2021-06-15 at 11 25 54" src="https://user-images.githubusercontent.com/3928502/122028680-8bf45480-cdcc-11eb-8af9-c4412caedd1d.png">

**Comment by nqlong-vlab** [comment]
Hi @agrignard, you should update the latest commit.
Scenario 0:
<img width="1157" alt="Screen Shot 2021-06-15 at 16 45 21" src="https://user-images.githubusercontent.com/74805596/122031903-54e86800-cdf9-11eb-846d-677edbf6cdc2.png">
Scenario 1:
<img width="1157" alt="Screen Shot 2021-06-15 at 16 45 27" src="https://user-images.githubusercontent.com/74805596/122031920-59148580-cdf9-11eb-855a-f4f8185dde10.png">
Scenario 2:
<img width="1157" alt="Screen Shot 2021-06-15 at 16 45 30" src="https://user-images.githubusercontent.com/74805596/122031931-5c0f7600-cdf9-11eb-9e3b-05f5313885c3.png">
Scenario 3:
<img width="1157" alt="Screen Shot 2021-06-15 at 16 45 45" src="https://user-images.githubusercontent.com/74805596/122031948-5fa2fd00-cdf9-11eb-8c90-6302a7648b27.png">

**Comment by agrignard** [comment]
Awesome
