### ISSUE TITLE
Decision between 3, 4 or 6 scenarios

### ISSUE THREAD

**Issue by LAAP** [CityScope/CSL_HCMC#25]
@LAAP: after working with Front_End, I figured out we will have 3 interaction models (plate) presenting 3 urban structures (landuse). So to control the year (2021/2030) (which will control the population), we must use tablet to send that signal. In that case, what will happen if audience select the year 2021 and load physical model as scenario 2? Technically we will have 6 scenarios: {scenario 0: 2021+interaction plate 1, scenario 1: 2030+ interaction plate 1, **missing**: 2021 + interaction plate 2, scenario 2: 2030 + interaction plate 2, **missing**: 2021 + interaction plate 3, scenario 3: 2030 + interaction plate 3}.
By thinking about it, I think of 2 options:
1. Revise our story telling
2. a mechanism to allow audience fit our only 4 scenarios.

Please lets me know your thinking. Thank you in advance

_Originally posted by @Hai-Hoang-88 in https://github.com/CityScope/CSL_HCMC/issues/1#issuecomment-868432621_

**Comment by LAAP** [comment]
Dear @Hai-Hoang-88 ,

From your text, it seams to me that we have the following scenarios:

scenario 0: 2021+interaction plate 1, 
scenario 1: 2030+ interaction plate 1, **missing: 2021 + interaction plate 2,** 
scenario 2: 2030 + interaction plate 2, **missing: 2021 + interaction plate 3,** 
scenario 3: 2030 + interaction plate 3

My suggestion is to make a new plate for scenario 1: 2030, so we have 4 plates, 1 plate for each of the 4 scenarios, and we do not show the missing ones. 
I know that scenario 0: 2021 and "scenario 1: 2030+ interaction plate 1", has the same buildings, however I still think that it makes sense to keep the methodology of 1 scenario per plate. Maybe "scenario 1: 2030+ interaction plate 1" can has a slightly different color on the transparent material, or something that differentiates the physical model  from "scenario 0: 2021+interaction plate 1", 

So, following my suggestion we could have:

scenario 0: 2021+interaction plate 1, 
scenario 1: 2030+ interaction plate 2, **missing: New plate**
scenario 2: 2030 + interaction plate 3, 
scenario 3: 2030 + interaction plate 4

Please, let me know your thoughts

**Comment by Hai-Hoang-88** [comment]
Dear @LAAP , It is also an option. I agree that it will be clear if we keep the methodology. 

With this option, we may need to discuss with hardware team for create another plate, software team on how to show it different but at the same time consistency, and maybe involve in tablet task.

I suggest a quick catch-up meeting to discuss about this and define what will be the best option to go.

**Comment by LAAP** [comment]
Hi @Hai-Hoang-88 ,

Yes, let's have a meeting between the Hardware and the software team and then we can decide the most efficient/convenient  solution

**Comment by agrignard** [comment]
I am also in favor++ to keep what is planned which is 4 scenarios and 4 plate. We can always (ones this is made) think about better solution but for now we need to stay on what was planned as some decision as already been taken in term fo design. 

If we all agree on that let's also close this issue to focus on the remaining ones

**Comment by agrignard** [comment]
We all agree that we for 3 scenarios (0,2 and 3). So I close this issue
